### PR TITLE
Challenge mode

### PR DESCRIPTION
**Pull request by DominykasDobkevicius**
+ Tasks tab
+ Challenge mode: flashcards (from a selected exam) appear in a random order and you have to guess what the answer is.
+ Statistics tab tracks highscores for each exam

### CODE REVIEW

**Review by PaulinaIvan — COMMENTED** [review]
This is amazing, though the text overflows if it's too long. Maybe we could add the same more button, as we did in the flashcards OR format the textbox so it wouldn't act like a flashcard and wrap the text?

**Comment by DominykasDobkevicius** [comment]
Made some improvements, should be ok now.

**Comment by PaulinaIvan** [comment]
Made it cleaner, hope it passes your inspection

**Review by JurasEz — APPROVED** [review]
Looks good, everything works.
Reminder for everyone that previously created tests will not work from now on :)

**Pull request merged**
